import { StyleSheet, Platform } from 'react-native';
import Colors from '@/constants/colors';
import { METALLIC_BORDER_COLOR, METALLIC_BORDER_COLOR_STRONG, METALLIC_SHADOW_COLOR } from '@/constants/metallic';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#021A0E' as const,
  },
  keyboardView: {
    flex: 1,
  },
  heroSection: {
    paddingTop: 64,
    paddingBottom: 28,
    paddingHorizontal: 24,
    position: 'relative' as const,
    overflow: 'hidden' as const,
  },
  heroContent: {
    zIndex: 10,
  },
  logoRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 14,
    marginBottom: 18,
  },
  logoBadge: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(74,222,128,0.15)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  logoBadgeInner: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: 'rgba(22,163,74,0.3)',
    borderWidth: 1.5,
    borderColor: 'rgba(110,231,163,0.35)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  logoLetter: {
    fontSize: 28,
    fontWeight: '900' as const,
    color: '#6EE7A3',
  },
  logoTextRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  logoLetterText: {
    fontSize: 26,
    fontWeight: '900' as const,
    color: '#6EE7A3',
  },
  logoRestText: {
    fontSize: 26,
    fontWeight: '900' as const,
    color: '#FFFFFF',
  },
  locationChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    marginTop: 3,
  },
  locationChipText: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: '500' as const,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    lineHeight: 30,
    letterSpacing: -0.4,
  },
  heroPills: {
    flexDirection: 'row' as const,
    gap: 12,
    marginTop: 14,
  },
  heroPill: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  heroPillDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  heroPillText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: 'rgba(255,255,255,0.75)',
  },
  bottomSheet: {
    flex: 1,
    backgroundColor: Colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -16,
    paddingTop: 8,
    paddingHorizontal: 20,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignSelf: 'center' as const,
    marginBottom: 14,
    marginTop: 6,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  welcomeHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginBottom: 20,
  },
  welcomeEmoji: {
    fontSize: 32,
  },
  selectTitle: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: Colors.text,
    letterSpacing: -0.5,
  },
  selectSubtitle: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  loginBigButton: {
    borderRadius: 20,
    overflow: 'hidden' as const,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR_STRONG,
    ...(Platform.OS !== 'web'
      ? { shadowColor: METALLIC_SHADOW_COLOR, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.5, shadowRadius: 6, elevation: 3 }
      : {}),
  },
  loginBigGradient: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 18,
    gap: 14,
    borderRadius: 20,
  },
  loginIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  loginBigTextWrap: {
    flex: 1,
  },
  loginBigTitle: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: '#FFFFFF',
    marginBottom: 2,
  },
  loginBigSubtitle: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.65)',
  },

  dividerRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginBottom: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  dividerText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: Colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  roleCard: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: Colors.card,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR,
    marginBottom: 10,
    ...(Platform.OS !== 'web'
      ? { shadowColor: METALLIC_SHADOW_COLOR, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.4, shadowRadius: 5, elevation: 2 }
      : {}),
  },
  roleIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 14,
  },
  roleContent: {
    flex: 1,
  },
  roleTitleRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginBottom: 3,
  },
  roleEmoji: {
    fontSize: 16,
  },
  roleTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: Colors.text,
  },
  roleSubtitle: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 17,
  },
  roleArrow: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginLeft: 8,
  },
  demoButton: {
    borderRadius: 16,
    overflow: 'hidden' as const,
    marginTop: 14,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: 'rgba(251,191,36,0.35)',
  },
  demoButtonInner: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 14,
    gap: 12,
    borderRadius: 16,
  },
  demoIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(251,191,36,0.18)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  demoTextWrap: {
    flex: 1,
  },
  demoTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#FBBF24',
    marginBottom: 2,
  },
  demoSubtitle: {
    fontSize: 11,
    color: 'rgba(251,191,36,0.7)',
  },
  supportCorner: {
    position: 'absolute' as const,
    top: 54,
    right: 16,
    zIndex: 20,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(110,231,163,0.35)',
  },
  supportCornerText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#E6FFF1',
    letterSpacing: 0.2,
  },
  trustBadges: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
  },
  trustBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 5,
  },
  trustText: {
    fontSize: 12,
    color: Colors.textMuted,
    fontWeight: '500' as const,
  },
  trustDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: Colors.textMuted,
    opacity: 0.4,
  },
  screenHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 14,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: Colors.card,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR_STRONG,
    ...(Platform.OS !== 'web'
      ? { shadowColor: METALLIC_SHADOW_COLOR, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 4, elevation: 2 }
      : {}),
  },
  screenHeaderTextWrap: {
    flex: 1,
  },
  screenHeaderLabel: {
    fontSize: 12,
    color: Colors.textMuted,
    marginBottom: 2,
  },
  screenHeaderTitle: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: Colors.text,
  },
  formCard: {
    backgroundColor: Colors.card,
    borderRadius: 22,
    padding: 16,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR_STRONG,
    gap: 10,
    ...(Platform.OS !== 'web'
      ? { shadowColor: METALLIC_SHADOW_COLOR, shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.5, shadowRadius: 8, elevation: 4 }
      : {}),
  },
  loginMethodTabs: {
    flexDirection: 'row' as const,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 12,
    padding: 3,
    gap: 3,
  },
  loginMethodTab: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  loginMethodTabActive: {
    backgroundColor: Colors.primary,
  },
  loginMethodTabText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.textMuted,
  },
  loginMethodTabTextActive: {
    color: '#FFFFFF',
  },
  inputWrap: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR,
    paddingHorizontal: 14,
    gap: 10,
  },
  inputInner: {
    flex: 1,
    paddingVertical: 13,
    fontSize: 15,
    color: Colors.text,
  },
  inputInnerFull: {
    flex: 1,
    paddingVertical: 13,
    fontSize: 15,
    color: Colors.text,
  },
  eyeButton: {
    paddingVertical: 13,
    paddingLeft: 8,
  },
  nameRow: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  nameInput: {
    flex: 1,
  },
  codeInputWrap: {
    justifyContent: 'center' as const,
  },
  codeInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: '700' as const,
    letterSpacing: 10,
    paddingVertical: 16,
    color: Colors.text,
    textAlign: 'center' as const,
  },
  addressSection: {
    marginTop: 2,
    gap: 8,
  },
  sectionLabelRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    marginBottom: 2,
  },
  addressLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
  },
  addrRow: {
    flexDirection: 'row' as const,
    gap: 8,
  },
  addrSmall: {
    flex: 1,
  },
  servicesSection: {
    marginTop: 4,
    paddingTop: 4,
  },
  servicesTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: Colors.text,
  },
  servicesSubtitle: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 4,
    marginBottom: 12,
    lineHeight: 17,
  },
  servicesGrid: {
    gap: 8,
  },
  serviceChip: {
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  serviceChipSelected: {
    backgroundColor: 'rgba(22,163,74,0.2)',
    borderColor: 'rgba(74,222,128,0.4)',
  },
  serviceIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  serviceChipText: {
    flex: 1,
    fontSize: 13,
    color: Colors.text,
    fontWeight: '600' as const,
  },
  serviceChipTextSelected: {
    color: '#FFFFFF',
  },
  serviceCheck: {
    width: 22,
    height: 22,
    borderRadius: 7,
    backgroundColor: Colors.primary,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  switchModeButton: {
    paddingVertical: 6,
    alignItems: 'center' as const,
  },
  switchModeText: {
    fontSize: 13,
    color: Colors.textSecondary,
  },
  switchModeLink: {
    color: Colors.primary,
    fontWeight: '700' as const,
  },
  forgotButton: {
    alignItems: 'center' as const,
    paddingVertical: 4,
  },
  forgotText: {
    fontSize: 13,
    color: Colors.primary,
    fontWeight: '600' as const,
  },
  verifyIconRow: {
    alignItems: 'center' as const,
    paddingVertical: 8,
  },
  verifyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(14,139,86,0.15)',
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  verifyDesc: {
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 22,
    marginBottom: 4,
  },
  verifyEmailHighlight: {
    color: Colors.text,
    fontWeight: '700' as const,
  },
  resendButton: {
    alignItems: 'center' as const,
    paddingVertical: 6,
  },
  resendText: {
    fontSize: 13,
    color: Colors.primary,
    fontWeight: '600' as const,
  },
  resendTextDisabled: {
    color: Colors.textMuted,
  },
  passwordMismatch: {
    fontSize: 12,
    color: '#EF4444',
    textAlign: 'center' as const,
    marginTop: -4,
  },
  footer: {
    fontSize: 11,
    color: Colors.textMuted,
    textAlign: 'center' as const,
    marginTop: 20,
    opacity: 0.6,
  },
  biometricButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: 'rgba(74,222,128,0.08)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR_STRONG,
    marginBottom: 16,
    gap: 14,
    ...(Platform.OS !== 'web'
      ? { shadowColor: METALLIC_SHADOW_COLOR, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 5, elevation: 2 }
      : {}),
  },
  biometricIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(74,222,128,0.12)',
    borderWidth: 1.5,
    borderColor: METALLIC_BORDER_COLOR,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  biometricTextWrap: {
    flex: 1,
  },
  biometricTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: Colors.text,
    marginBottom: 2,
  },
  biometricSubtitle: {
    fontSize: 12,
    color: '#4ADE80',
    fontWeight: '600' as const,
  },
  termsRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  termsCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginTop: 1,
  },
  termsCheckboxActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  termsText: {
    flex: 1,
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 18,
  },
  termsLink: {
    color: Colors.primary,
    fontWeight: '600' as const,
    textDecorationLine: 'underline' as const,
  },
});
